// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/libing/Desktop/Study/serverless/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/libing/Desktop/Study/serverless/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/libing/Desktop/Study/serverless/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
